# Generated by Django 4.0.2 on 2026-01-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
